name: studiotwofour-5

volumes:
  data:
    driver: local

services:
      
  database:
    image: postgres
    restart: on-failure
    ports:
      - 9901:5432
    environment:
      POSTGRES_PASSWORD: 123454321
      POSTGRES_USER: studiotwofour_user
      POSTGRES_DB: studiotwofour
    volumes:
      - data:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    restart: on-failure
    ports:
      - 9902:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass 123454321
    volumes: 
      - data:/data